---
AWSTemplateFormatVersion: '2010-09-09'
Description: Demo Custom CFN provider - EFS Provisioned Throughput
Resources:
  EFS:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: False
  EfsProvisionedThroughput:
    Type: Custom::EfsProvisionedThroughput
    Properties:
      FileSystemId: !Ref EFS
      ThroughputMode: provisioned
      ProvisionedThroughputInMibps: 0.5
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-efs-provisioned-throughput-provider'
